using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RopeStep : MonoBehaviour
{
    // Start is called before the first frame update

    [SerializeField] private MaintenanceManager manager;
    [SerializeField] private bool missing;


    void Awake()
    {
    }

    // Update is called once per frame
    void OnEnable()
    {
        if (missing)
        {
            manager.CompleteStep("Vedlikehold", "Runde P책 Ring", "Legg til tau p책 merd");
        }
        else
        {
            manager.CompleteStep("Vedlikehold", "Runde P책 Ring", "Reparer tau p책 merd");
        }
        manager.PlaySuccess();
    }


}


